version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns: ["@angular/*", "angular-eslint"]
      eslint:
        patterns: ["eslint*", "typescript-eslint"]
