import { VERSION } from '../constants.js';
import type { RemediationItem, ScanResult } from '../types.js';

const escapeMarkdown = (s: string): string => s.replace(/\|/g, '\\|');

const priorityEmoji = (p: RemediationItem['priority']): string =>
  p === 'high' ? '🔴' : p === 'medium' ? '🟡' : '🟢';

export const generatePrSummary = (result: ScanResult): string => {
  const lines: string[] = [];

  lines.push('## ng-xray Health Report');
  lines.push('');
  lines.push(`**Score: ${result.score.overall}/100** — ${result.score.label}`);
  lines.push('');

  if (result.scanStatus === 'partial' && result.failedAnalyzers.length > 0) {
    lines.push(`> ⚠️ Partial scan — ${result.failedAnalyzers.length} analyzer(s) failed: ${result.failedAnalyzers.join(', ')}`);
    lines.push('');
  }

  lines.push('| Category | Score | Issues |');
  lines.push('|----------|-------|--------|');
  for (const c of result.score.categories) {
    lines.push(`| ${escapeMarkdown(c.label)} | ${c.score}/${c.maxDeduction} | ${c.issueCount} |`);
  }
  lines.push('');

  const topFixes = result.remediation.slice(0, 5);
  if (topFixes.length > 0) {
    lines.push('### Top Fixes');
    lines.push('');
    for (const r of topFixes) {
      lines.push(`- ${priorityEmoji(r.priority)} ${escapeMarkdown(r.description)} — +${r.estimatedScoreImpact} pts, ${r.affectedFileCount} file${r.affectedFileCount === 1 ? '' : 's'}`);
    }
    lines.push('');
  }

  lines.push(`*Generated by ng-xray v${VERSION}*`);

  return lines.join('\n');
};
